### ISSUE TITLE
Flag is misogynist due to colour similarity with menstrual blood

### ISSUE THREAD

**Issue by rightfold** [jarcane/red-flag-of-fp#5]
Please change the colour to not discriminate against female programmers.

**Comment by JX7P** [comment]
Respectfully speaking, this is ludicrous and you are a troll.

**Comment by jarcane** [comment]
Quite.

The repo got posted on Reddit. I expect a fair few more like this once the Americans wake up.

**Comment by ke7ofi** [comment]
Nice strawmyn, @rightfold.
