### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by ptrkrlsrd** [jarcane/red-flag-of-fp#6]
Hey,

I love this project! Both aesthetically and the thought behind it. Therefore I'd love to have it on my laptop, and bet there are others with me. Have you thought about creating stickers with the flag on it, or do you rather think people should create the stickers themself?

**Comment by jarcane** [comment]
I could possibly do so. Do you know of a POD service for this? I only know of StickerMule, which would I think mean batch preordering, and I don't know there's enough interest yet to want to buy a ton of them on spec.

**Comment by ptrkrlsrd** [comment]
I don't know any, but I can do some research. I iniitially searched Redbubble for stickers with your flag on it, so maybe thats an option?

**Comment by jarcane** [comment]
I'll take a look at that. I also looked at Zazzle and they have a rectangular sticker that's just about close enough proportions to work.

**Comment by jarcane** [comment]
So I'm no longer able to get the original SVG files to render correctly with the current versions of Inkscape and Source Code Pro, but I was able to create some stickers on RedBubble of all the variant designs from the existing PNG versions.

You can find the store here: https://www.redbubble.com/people/annarcana/shop?asc=u

I will be ordering a batch, but I can't vouch for how well it looks in the real until I get mine.

**Comment by ptrkrlsrd** [comment]
@jarcane Awesome! Gonna order some myself and put on my laptop.

**Comment by jarcane** [comment]
@ptrkrlsrd got my samples. They look alright in small size, though I think they'd start looking a bit pixelly in higher sizes. Main thing I don't like is the white border; seems they don't do edge to edge stickers at Redbubble.
