### ISSUE TITLE
SVG files have bit-rotted

### ISSUE THREAD

**Issue by jarcane** [jarcane/red-flag-of-fp#7]
So it seems that Inkscape has changed its formats, and so the SVG files no longer load correctly in the current version. In addition, I struggled to adjust a converted version properly to match the original design, I think something has changed with the version of Source Code Pro I was using as well.

It would probably be advisable then to reconstruct the design in proper universal SVG format.

Volunteers welcome.

**Comment by Devvypaws** [comment]
When I tried using older releases of Source Code Pro to see if something changed between versions, I couldn't get the lambda to match the render. I tried a few different free fonts and I was finally able to recreate it pretty faithfully with DejaVu Sans. 

Unfortunately, Google Web Fonts doesn't have DejaVu Sans. In eb9e9f4, you mention this was part of why Source Code Pro was chosen. One possibility is the text could be turned into a path and that would eliminate the font dependency altogether.

**Comment by jarcane** [comment]
Thanks for looking at this! Yeah, that was the same problem I had. For some reason I couldn't get the shape and even glyph itself of the lambda to match the original. 

I think you're right on the solution though. It doesn't really matter which open source font is used if it matches the design and the lambda is converted to an actual shape instead of a text object. Then it should render fine no matter what.

**Comment by jarcane** [comment]
Resolved by #8 and @68kHeart's hard work!
